dbt_workshop:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: 'workshop'
      schema: 'main'
      schema_directory: '/home/coder/project/data'
      schemas_and_paths:
        main: '/home/coder/project/data/workshop.db'

