dbt_workshop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES_PORT', 5432) | int }}"
      user: "{{ env_var('POSTGRES_USER', 'dbt_user') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'dbt_password') }}"
      dbname: "{{ env_var('POSTGRES_DB', 'dbt_workshop') }}"
      schema: olist_data
      threads: 4
      keepalives_idle: 0
      connect_timeout: 10
      search_path: olist_data,public

    # Legacy SQLite output for reference
    sqlite:
      type: sqlite
      threads: 1
      database: 'workshop'
      schema: 'main'
      schema_directory: '/home/coder/project/data'
      schemas_and_paths:
        main: '/home/coder/project/data/workshop.db'

