-- TODO: This file should be completed in Session 2, Challenge 1
-- Task: Create a staging model for order items using a variable for snapshot date
--
-- Instructions: See exercises/session2_hands_on.html - Challenge 1
