-- TODO: This file should be completed in Session 2, Challenge 4
-- Task: Create staging model for late-arriving orders with ingestion tracking
--
-- Instructions: See exercises/session2_hands_on.html - Challenge 4
