-- TODO: This file should be completed in Session 3, Challenge 2b
-- Task: Create behavioral features mart with product/seller diversity and payment patterns
--
-- Instructions: See exercises/session3_hands_on.html - Challenge 2b
