-- TODO: This file should be completed in Session 3, Challenge 1
-- Task: Create enriched mart table joining customer features with geographic seed data
--
-- Instructions: See exercises/session3_hands_on.html - Challenge 1
